remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "neon"
locale: "en-US"

title: r2alter blog
subtitle: Some words about my projects

name: Marcin Winiarek
url: https://r2alter.github.io


author:
  name     : "r2alter"
  avatar   : "/assets/images/r2-logo.jpg"
  bio      : "Red teamer and privacy fighter."
  links    :
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/r2alter"


plugins:
  - jekyll-include-cache